name: tox

on: [push]

jobs:
  tox:
    services:
      redis:
        image: redis
        ports:
        - 6379/tcp
        options: --entrypoint redis-server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Test with Tox
      run: |
        pip install tox
        tox
      env:
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}